[build]
  command = "npm run build"
  publish = "public"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@sparticuz/chromium"]

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "echo 'Starting Netlify Functions server'"
  port = 8888
  targetPort = 3000
  framework = "#static"
  autoLaunch = true