[build]
  command = "rm -rf netlify/functions/check-engage-auth/node_modules && npm run build"
  publish = "dist"
  functions = "netlify/functions"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF netlify/functions/check-engage-auth/"

[build.environment]
  NETLIFY_CLEAR_CACHE = "true"
  NODE_ENV = "production"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

[dev]
  command = "echo 'Starting Netlify Dev server'"
  port = 8888
  framework = "#custom"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200