[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NETLIFY_CLEAR_CACHE = "true"
  NODE_ENV = "production"
  CACHE_BUST = "2025-03-24-001"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = []

[dev]
  command = "echo 'Starting Netlify Dev server'"
  port = 8888
  framework = "#custom"
  autoLaunch = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200